{% set name = "cvprac" %}
{% set version = "1.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5f0e5249c7e73d3c6f10a698be57f50382073773e6c81d74640fcc4976b602e5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
    - requests[socks] >=2.27.0
  run:
    - python
    - requests[socks] >=2.27.0

test:
  imports:
    - cvprac
    - cvprac/__pycache__

about:
  home: "https://github.com/aristanetworks/cvprac"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Arista Cloudvision(R) Portal Rest API Client written in python"
  doc_url: 
  dev_url: 

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48416
    reason: Client request
  recipe-maintainers:
    - ianaobi
